# Generated by Django 5.2.17 on 2026-09-30 13:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('kind', models.CharField(choices=[('credit', 'Bank krediti'), ('personal', 'Tanishdan qarz'), ('nasiya', 'Nasiya'), ('other', 'Boshqa')], default='credit', max_length=16)),
                ('total', models.BigIntegerField(verbose_name='Umumiy summa')),
                ('paid', models.BigIntegerField(default=0, verbose_name="To'langan")),
                ('monthly_payment', models.BigIntegerField(default=0, verbose_name="Oylik to'lov")),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarzlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name="Summa (so'm)")),
                ('source', models.CharField(choices=[('salary', 'Oylik maosh'), ('extra', "Qo'shimcha daromad"), ('business', 'Biznes / savdo'), ('other', 'Boshqa')], default='salary', max_length=16)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daromad',
                'verbose_name_plural': 'Daromadlar',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Saboq raqami')),
                ('title', models.CharField(max_length=150, verbose_name='Mavzu')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='Video chiqqan sana')),
                ('youtube_id', models.CharField(blank=True, help_text='Masalan https://youtu.be/AbCdEf12345 uchun: AbCdEf12345', max_length=32, verbose_name='YouTube video ID')),
                ('summary', models.TextField(verbose_name='Qisqacha mazmun')),
                ('key_points', models.TextField(blank=True, help_text='Har bir saboq alohida qatorda', verbose_name='Saboqlar')),
                ('tasks', models.TextField(blank=True, help_text='Har bir vazifa alohida qatorda', verbose_name='Nima qilish kerak')),
                ('task_type', models.CharField(choices=[('read', "Faqat ko'rish va belgilash"), ('note', 'Fikr yozish'), ('income', 'Daromad kiritish'), ('expense', 'Xarajat kiritish'), ('save', '10% zaxiraga ajratish'), ('debt_list', "Qarzlar ro'yxatini tuzish"), ('debt_plan', "Qarz rejasini ko'rish"), ('debt_pay', "Qarzga to'lov qilish")], default='read', help_text="Saboqni yakunlash uchun ilovada nima qilingan bo'lishi kerak", max_length=16, verbose_name='Ilovadagi amal')),
                ('note_prompt', models.CharField(blank=True, max_length=200, verbose_name='Savol (fikr yozish uchun)')),
                ('is_published', models.BooleanField(default=True, verbose_name="Foydalanuvchilarga ko'rinadi")),
            ],
            options={
                'verbose_name': 'Saboq',
                'verbose_name_plural': 'Saboqlar',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='Familiya')),
                ('username', models.CharField(blank=True, max_length=64)),
                ('photo_url', models.URLField(blank=True, max_length=512)),
                ('monthly_income', models.BigIntegerField(default=0, help_text="Foydalanuvchi o'zi kiritadi; 10% va qarz rejasi shunga qarab hisoblanadi", verbose_name='Oylik daromad')),
                ('notify', models.BooleanField(default=True, verbose_name='Eslatmalar yoqilgan')),
                ('accepted_disclaimer', models.BooleanField(default=False)),
                ('bot_started', models.BooleanField(default=False, verbose_name='Botni ishga tushirgan')),
                ('bot_blocked', models.BooleanField(default=False, verbose_name='Botni bloklagan')),
                ('last_morning_date', models.DateField(blank=True, null=True)),
                ('last_evening_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.debt')),
            ],
            options={
                'verbose_name': "Qarz to'lovi",
                'verbose_name_plural': "Qarz to'lovlari",
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name="Summa (so'm)")),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings', to='core.income')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='core.tguser')),
            ],
            options={
                'verbose_name': 'Zaxira',
                'verbose_name_plural': 'Zaxiralar',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tguser')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='core.tguser'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name="Summa (so'm)")),
                ('category', models.CharField(choices=[('food', 'Oziq-ovqat'), ('transport', "Yo'lkira"), ('utility', 'Kommunal'), ('other', 'Boshqalar')], default='other', max_length=16)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.tguser')),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='debt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='core.tguser'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.tguser')),
            ],
            options={
                'verbose_name': 'Bajarilgan saboq',
                'verbose_name_plural': 'Bajarilgan saboqlar',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
