# Generated by Django 5.2.17 on 2026-09-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='income_type',
            field=models.CharField(blank=True, choices=[('', 'Tanlanmagan'), ('salary', 'Oylik oladi'), ('irregular', "Oylik olmaydi (daromadi o'zgaruvchan)")], default='', max_length=16, verbose_name='Daromad turi'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='save_percent',
            field=models.PositiveSmallIntegerField(default=10, help_text='Daromadning necha foizi zaxiraga ajratiladi (1–50)', verbose_name="O'ziga to'lash foizi"),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='monthly_income',
            field=models.BigIntegerField(default=0, help_text="Foydalanuvchi o'zi kiritadi; zaxira va qarz rejasi shunga qarab hisoblanadi", verbose_name='Oylik daromad'),
        ),
    ]
