# Generated by Django 5.2.17 on 2026-09-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_income_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name="Asosiy qarz qoldig'i"),
        ),
        migrations.AddField(
            model_name='debt',
            name='extra_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Qo'shib to'lash foizi"),
        ),
        migrations.AddField(
            model_name='debt',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Yillik foiz'),
        ),
        migrations.AddField(
            model_name='debt',
            name='principal',
            field=models.BigIntegerField(default=0, verbose_name='Olingan summa'),
        ),
        migrations.AddField(
            model_name='debt',
            name='term_months',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Muddat (oy)'),
        ),
    ]
