# Generated by Django 5.2.17 on 2026-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_credit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='need',
            field=models.CharField(blank=True, choices=[('zarur', 'Zarur'), ('kerak', 'Kerak'), ('havas', 'Havas')], default='', max_length=8, verbose_name='Zarur/Kerak/Havas'),
        ),
    ]
