# Generated by Django 5.2.17 on 2026-09-30 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expense_need'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='bucket',
            field=models.CharField(choices=[('guard', "Qo'riqchi pul"), ('grow', "O'sadigan pul")], default='guard', max_length=8, verbose_name='Qism'),
        ),
        migrations.AddField(
            model_name='saving',
            name='group',
            field=models.CharField(blank=True, help_text="O'tkazmaning ikki yozuvini bog'laydi", max_length=32),
        ),
        migrations.AddField(
            model_name='saving',
            name='kind',
            field=models.CharField(choices=[('deposit', "Qo'shildi"), ('withdraw', 'Olindi'), ('transfer', "O'tkazildi")], default='deposit', max_length=10, verbose_name='Turi'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='guard_months',
            field=models.PositiveSmallIntegerField(default=3, help_text="Qo'riqchi pul necha oylik xarajatga yetishi kerak (3–6)", verbose_name="Qo'riqchi pul necha oylik"),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Oziq-ovqat'), ('rent', 'Ijara / uy'), ('utility', 'Kommunal'), ('transport', "Yo'lkira"), ('clothes', 'Kiyim-kechak'), ('health', "Sog'liq"), ('education', "Ta'lim"), ('phone', 'Aloqa / internet'), ('events', "To'y-marosim"), ('charity', 'Sadaqa / ehson'), ('other', 'Boshqalar')], default='other', max_length=16),
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('amount', models.BigIntegerField(verbose_name="Summa (so'm)")),
                ('category', models.CharField(choices=[('food', 'Oziq-ovqat'), ('rent', 'Ijara / uy'), ('utility', 'Kommunal'), ('transport', "Yo'lkira"), ('clothes', 'Kiyim-kechak'), ('health', "Sog'liq"), ('education', "Ta'lim"), ('phone', 'Aloqa / internet'), ('events', "To'y-marosim"), ('charity', 'Sadaqa / ehson'), ('other', 'Boshqalar')], default='other', max_length=16)),
                ('need', models.CharField(blank=True, choices=[('zarur', 'Zarur'), ('kerak', 'Kerak'), ('havas', 'Havas')], default='zarur', max_length=8)),
                ('day', models.PositiveSmallIntegerField(default=1, verbose_name='Oyning qaysi kuni')),
                ('active', models.BooleanField(default=True)),
                ('last_month', models.CharField(blank=True, help_text='YYYY-MM', max_length=7, verbose_name='Oxirgi yozilgan oy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring', to='core.tguser')),
            ],
            options={
                'verbose_name': 'Oylik majburiy xarajat',
                'verbose_name_plural': 'Oylik majburiy xarajatlar',
                'ordering': ['day', 'id'],
            },
        ),
    ]
