# Generated by Django 5.2.17 on 2026-09-30 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jamgarma_recurring'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('login', 'Kirdi'), ('income_add', 'Kirim yozdi'), ('income_edit', 'Kirimni tahrirladi'), ('expense_add', 'Xarajat yozdi'), ('expense_edit', 'Xarajatni tahrirladi'), ('entry_delete', "Yozuvni o'chirdi"), ('saving_add', "Jamg'armaga qo'shdi"), ('saving_withdraw', "Jamg'armadan oldi"), ('saving_transfer', "Jamg'arma ichida o'tkazdi"), ('debt_add', "Qarz qo'shdi"), ('debt_pay', "Qarz to'ladi"), ('debt_close', 'Qarzni yopdi'), ('lesson_complete', 'Saboqni yakunladi'), ('settings', "Sozlamalarni o'zgartirdi"), ('recurring_add', "Majburiy xarajat qo'shdi"), ('bot_start', 'Botni ishga tushirdi'), ('bot_block', 'Botni blokladi')], max_length=24)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Amal',
                'verbose_name_plural': 'Amallar jurnali',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Matn')),
                ('audience', models.CharField(choices=[('all', 'Barcha (eslatmalari yoqilgan)'), ('active7', 'Oxirgi 7 kunda kirganlar'), ('inactive7', '7 kundan beri kirmaganlar')], default='all', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('sending', 'Yuborilmoqda'), ('done', 'Yuborildi'), ('failed', 'Xato')], db_index=True, default='pending', max_length=10)),
                ('total', models.PositiveIntegerField(default=0)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('last_user_id', models.BigIntegerField(default=0, help_text='Qayta ishga tushganda shu yerdan davom etadi')),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ommaviy xabar',
                'verbose_name_plural': 'Ommaviy xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ['-date', '-id'], 'verbose_name': "Jamg'arma harakati", 'verbose_name_plural': "Jamg'arma harakatlari"},
        ),
        migrations.AddField(
            model_name='tguser',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Admin izohi'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='is_active',
            field=models.BooleanField(default=True, help_text="O'chirilsa, foydalanuvchi ilovaga kira olmaydi", verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='logincode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='last_seen',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['debt', 'date'], name='debtpay_debt_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='expense_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'date'], name='income_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='saving',
            index=models.Index(fields=['user', 'date'], name='saving_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='saving',
            index=models.Index(fields=['user', 'bucket'], name='saving_user_bucket_idx'),
        ),
        migrations.AddIndex(
            model_name='tguser',
            index=models.Index(fields=['notify', 'bot_started', 'bot_blocked'], name='tguser_reminder_idx'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='core.tguser'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lesson', verbose_name="Saboq e'loni"),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='activity_user_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-created_at'], name='activity_action_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='activity_created_idx'),
        ),
    ]
