# Generated by Django 5.2.17 on 2026-09-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_scale_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='currency',
            field=models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], default='UZS', max_length=3, verbose_name='Hisob valyutasi'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='currency_chosen',
            field=models.BooleanField(default=False, verbose_name='Valyutani tanlagan'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='onboarding_hidden',
            field=models.BooleanField(default=False, verbose_name="«Boshlash yo'li» yashirilgan"),
        ),
    ]
