# Generated by Django 5.2.17 on 2026-09-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_currency_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('login', 'Kirdi'), ('income_add', 'Kirim yozdi'), ('income_edit', 'Kirimni tahrirladi'), ('expense_add', 'Xarajat yozdi'), ('expense_edit', 'Xarajatni tahrirladi'), ('entry_delete', "Yozuvni o'chirdi"), ('saving_add', "Jamg'armaga qo'shdi"), ('saving_withdraw', "Jamg'armadan oldi"), ('saving_transfer', "Jamg'arma ichida o'tkazdi"), ('debt_add', "Qarz qo'shdi"), ('debt_pay', "Qarz to'ladi"), ('debt_close', 'Qarzni yopdi'), ('lesson_complete', 'Saboqni yakunladi'), ('settings', "Sozlamalarni o'zgartirdi"), ('recurring_add', "Majburiy xarajat qo'shdi"), ('bot_start', 'Botni ishga tushirdi'), ('bot_block', 'Botni blokladi'), ('bot_report', "Botda hisobot ko'rdi")], max_length=24),
        ),
    ]
