# Generated by Django 5.2.17 on 2026-09-30 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bot_report_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(blank=True, help_text='https://baraka.uz — canonical va sitemap uchun', verbose_name='Sayt manzili')),
                ('title', models.CharField(blank=True, help_text="Google natijasida ko'rinadi. 50–60 belgi ideal", max_length=70, verbose_name='Sarlavha (title)')),
                ('description', models.CharField(blank=True, help_text='Google natijasida sarlavha ostida. 140–160 belgi ideal', max_length=170, verbose_name='Tavsif (meta description)')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name="Kalit so'zlar")),
                ('og_title', models.CharField(blank=True, max_length=90, verbose_name='Ulashishda sarlavha')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='Ulashishda tavsif')),
                ('google_verification', models.CharField(blank=True, help_text="google-site-verification content qiymati (fayl o'rniga)", max_length=120, verbose_name='Google meta-teg kodi')),
                ('yandex_verification', models.CharField(blank=True, max_length=120, verbose_name='Yandex meta-teg kodi')),
                ('analytics_id', models.CharField(blank=True, help_text='G-XXXXXXXXXX', max_length=32, verbose_name='Google Analytics ID')),
                ('robots_extra', models.TextField(blank=True, verbose_name="robots.txt qo'shimcha qatorlari")),
                ('allow_indexing', models.BooleanField(default=True, verbose_name='Qidiruv tizimlariga ochiq')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO sozlamalari',
                'verbose_name_plural': 'SEO sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='VerificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, unique=True, verbose_name='Fayl nomi')),
                ('content', models.TextField(max_length=10000, verbose_name='Mazmuni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tasdiqlash fayli',
                'verbose_name_plural': 'Tasdiqlash fayllari',
                'ordering': ['filename'],
            },
        ),
        migrations.AddField(
            model_name='tguser',
            name='rating_asked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Baho so'ralgan"),
        ),
        migrations.AddField(
            model_name='tguser',
            name='rating_asks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tguser',
            name='token_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tguser',
            name='uid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tguser',
            name='visits',
            field=models.PositiveIntegerField(default=1, help_text='30 daqiqadan uzoq tanaffusdan keyingi har kirish', verbose_name='Kirishlar soni'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('login', 'Kirdi'), ('income_add', 'Kirim yozdi'), ('income_edit', 'Kirimni tahrirladi'), ('expense_add', 'Xarajat yozdi'), ('expense_edit', 'Xarajatni tahrirladi'), ('entry_delete', "Yozuvni o'chirdi"), ('saving_add', "Jamg'armaga qo'shdi"), ('saving_withdraw', "Jamg'armadan oldi"), ('saving_transfer', "Jamg'arma ichida o'tkazdi"), ('debt_add', "Qarz qo'shdi"), ('debt_pay', "Qarz to'ladi"), ('debt_close', 'Qarzni yopdi'), ('lesson_complete', 'Saboqni yakunladi'), ('settings', "Sozlamalarni o'zgartirdi"), ('recurring_add', "Majburiy xarajat qo'shdi"), ('bot_start', 'Botni ishga tushirdi'), ('bot_block', 'Botni blokladi'), ('bot_report', "Botda hisobot ko'rdi"), ('feedback', 'Baho qoldirdi'), ('logout_all', 'Barcha qurilmalardan chiqdi')], max_length=24),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Baho')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='Fikr')),
                ('page', models.CharField(blank=True, max_length=32)),
                ('is_read', models.BooleanField(default=False, verbose_name="Ko'rildi")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.tguser')),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
                'ordering': ['-created_at'],
            },
        ),
    ]
