# Generated by Django 5.2.17 on 2026-10-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tguser_uid_fill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_youtube', models.URLField(blank=True, verbose_name='Abdukarim Mirzayev — YouTube')),
                ('author_instagram', models.URLField(blank=True, verbose_name='Abdukarim Mirzayev — Instagram')),
                ('author_telegram', models.URLField(blank=True, verbose_name='Abdukarim Mirzayev — Telegram kanal')),
                ('contact_telegram', models.CharField(blank=True, help_text='@username — savollar uchun', max_length=64, verbose_name='Telegram (admin)')),
                ('contact_channel', models.URLField(blank=True, verbose_name='Bizning Telegram kanal')),
                ('contact_instagram', models.URLField(blank=True, verbose_name='Bizning Instagram')),
                ('contact_phone', models.CharField(blank=True, help_text='+998 90 123 45 67', max_length=32, verbose_name='Telefon')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_hours', models.CharField(blank=True, help_text='Masalan: Har kuni 9:00–21:00', max_length=80, verbose_name='Ish vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
