# Generated by Django 5.2.17 on 2026-10-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Oziq-ovqat'), ('rent', 'Ijara / uy'), ('utility', 'Kommunal'), ('transport', "Yo'lkira"), ('clothes', 'Kiyim-kechak'), ('health', "Sog'liq"), ('education', "Ta'lim"), ('phone', 'Aloqa / internet'), ('events', "To'y-marosim"), ('charity', 'Sadaqa / ehson'), ('shopping', 'Xaridlar'), ('other', 'Boshqalar')], default='other', max_length=16),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.CharField(choices=[('food', 'Oziq-ovqat'), ('rent', 'Ijara / uy'), ('utility', 'Kommunal'), ('transport', "Yo'lkira"), ('clothes', 'Kiyim-kechak'), ('health', "Sog'liq"), ('education', "Ta'lim"), ('phone', 'Aloqa / internet'), ('events', "To'y-marosim"), ('charity', 'Sadaqa / ehson'), ('shopping', 'Xaridlar'), ('other', 'Boshqalar')], default='other', max_length=16),
        ),
    ]
