# Generated by Django 5.2.17 on 2026-10-02 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_shopping_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lent_debts', to='core.tguser', verbose_name="Qarz bergan (bog'langan)"),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='status',
            field=models.CharField(choices=[('ok', 'Hisobga olingan'), ('pending', 'Tasdiq kutilmoqda'), ('rejected', 'Rad etilgan')], default='ok', max_length=8),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('login', 'Kirdi'), ('income_add', 'Kirim yozdi'), ('income_edit', 'Kirimni tahrirladi'), ('expense_add', 'Xarajat yozdi'), ('expense_edit', 'Xarajatni tahrirladi'), ('entry_delete', "Yozuvni o'chirdi"), ('saving_add', "Jamg'armaga qo'shdi"), ('saving_withdraw', "Jamg'armadan oldi"), ('saving_transfer', "Jamg'arma ichida o'tkazdi"), ('debt_add', "Qarz qo'shdi"), ('debt_pay', "Qarz to'ladi"), ('debt_close', 'Qarzni yopdi'), ('lesson_complete', 'Saboqni yakunladi'), ('settings', "Sozlamalarni o'zgartirdi"), ('recurring_add', "Majburiy xarajat qo'shdi"), ('bot_start', 'Botni ishga tushirdi'), ('bot_block', 'Botni blokladi'), ('bot_report', "Botda hisobot ko'rdi"), ('feedback', 'Baho qoldirdi'), ('logout_all', 'Barcha qurilmalardan chiqdi'), ('debt_invite', 'Qarz uchun havola yaratdi'), ('debt_link', "Qarzni tasdiqladi (bog'landi)"), ('debt_unlink', "Qarz bog'lanishini uzdi")], max_length=24),
        ),
        migrations.CreateModel(
            name='DebtLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('direction', models.CharField(choices=[('borrowed', 'Qarz oldim'), ('lent', 'Qarz berdim')], max_length=8)),
                ('amount', models.BigIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Kimga / izoh')),
                ('status', models.CharField(choices=[('open', 'Kutilmoqda'), ('accepted', 'Tasdiqlandi'), ('declined', 'Rad etildi'), ('cancelled', 'Bekor qilindi')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_links', to='core.tguser')),
                ('debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.debt')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tguser')),
            ],
            options={
                'verbose_name': 'Qarz taklifi',
                'verbose_name_plural': 'Qarz takliflari',
                'ordering': ['-created_at'],
            },
        ),
    ]
