# Generated by Django 5.2.17 on 2026-10-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_debt_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Telegram Premium'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='photo_url',
            field=models.URLField(blank=True, max_length=512, verbose_name='Profil rasmi'),
        ),
    ]
