from django.urls import path, re_path

from . import api, pwa, seo, views

urlpatterns = [
    path("manifest.webmanifest", pwa.manifest, name="manifest"),
    path("sw.js", pwa.service_worker, name="service_worker"),
    path("oflayn/", pwa.offline, name="offline"),
    path("robots.txt", seo.robots_txt),
    path("sitemap.xml", seo.sitemap_xml),
    re_path(r"^(?P<filename>google[0-9a-f]+\.html|yandex_[0-9a-f]+\.html|BingSiteAuth\.xml)$", seo.verification_file),
    path("", views.landing, name="landing"),
    path("asosiy/", views.home, name="home"),
    path("hamyon/", views.wallet, name="wallet"),
    path("qarzlar/", views.debts, name="debts"),
    path("saboqlar/", views.lessons, name="lessons"),
    path("saboqlar/<int:number>/", views.lesson, name="lesson"),
    path("jamgarma/", views.savings, name="savings"),
    path("sozlamalar/", views.settings_page, name="settings"),
    path("haqida/", views.about, name="about"),
    path("kalkulyator/", views.calculators, name="calculators"),
    path("hisobot/", views.report, name="report"),
    path("aloqa/", views.contact, name="contact"),
    path("kirish/", views.login, name="login"),
    path("api/auth/telegram", api.auth_telegram),
    path("api/auth/login-code", api.auth_login_code),
    path("api/auth/dev-login", api.auth_dev_login),
    path("api/auth/login-status", api.auth_login_status),
    path("api/me", api.me),
    path("api/me/currency", api.set_currency),
    path("api/me/logout-all", api.logout_all),
    path("api/me/app-installed", api.app_installed),
    path("api/feedback", api.feedback),
    path("api/feedback/shown", api.feedback_shown),
    path("api/rates", api.usd_rate),
    path("api/site", api.site_info),
    path("api/report", api.report),
    path("api/wallet", api.wallet),
    path("api/incomes", api.income_create),
    path("api/expenses", api.expense_create),
    path("api/savings", api.saving_create),
    path("api/savings/withdraw", api.saving_withdraw),
    path("api/savings/transfer", api.saving_transfer),
    path("api/jamgarma", api.jamgarma),
    path("api/recurring", api.recurring),
    path("api/recurring/<int:pk>", api.recurring_detail),
    path("api/entries", api.entries),
    path("api/entries/<str:kind>/<int:pk>", api.entry_detail),
    path("api/debts", api.debts),
    path("api/debts/plan", api.debt_plan),
    path("api/debts/<int:pk>", api.debt_detail),
    path("api/debts/<int:pk>/pay", api.debt_pay),
    path("api/debts/<int:pk>/invite", api.debt_invite),
    path("api/debts/<int:pk>/unlink", api.debt_unlink),
    path("api/debts/lend", api.debt_lend),
    path("api/debts/invites/<int:pk>", api.debt_invite_cancel),
    path("api/debts/payments/<int:pk>/review", api.debt_payment_review),
    path("api/lessons", api.lessons),
    path("api/lessons/<int:number>", api.lesson_detail),
    path("api/lessons/<int:number>/complete", api.lesson_complete),
]
